enableemoji = true
baseURL = 'https://projectoriented.github.io/'
languageCode = 'en-us'
title = 'A data explorer'
copyright = 'Mei Wu'
theme = "themes/hugo-theme-cactus"

[params]
colortheme = "white"

# Home page settings
description = "👋 Welcome! I am Mei (pronounced as MAY) and this is a space where I continue to learn biology 🧬 and USA politics through data visualization. I will also blog about the pervasive thoughts that fill my day."
mainSectionTitle = "📖 Writings"
mainSection = "posts"
postsOnHomePage = 5

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
name = "github"
url = "https://github.com/projectoriented/"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/projectoriented/"
