baseURL = 'https://projectoriented.github.io/'
languageCode = 'en-us'
title = 'meiwu'
theme = "hugo-coder"

[params]
author = "Mei Wu"
description = "Mei Wu's personal website"
keywords = "bioinformatician,developer,personal,blog"
info = ["Bioinformatician"]
avatarURL = "images/profile_2021.jpeg"
colorScheme = "auto"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/projectoriented/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/projectoriented/"
